const {entries,racers,events}=window.WORLD;const main=document.querySelector('main');let group='s5',series='ALL',outfit='race';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const inline=s=>esc(s).replace(/\*\*(.*?)\*\*/g,'<b>$1</b>').replace(/`([^`]+)`/g,'<b>$1</b>');
function prose(s){return '<div class="prose">'+s.split('\n').map(l=>{let h=l.match(/^#{1,4} (.*)/);return h?`<h3>${inline(h[1])}</h3>`:l.startsWith('- ')?`<div class="line">• ${inline(l.slice(2))}</div>`:l?`<p>${inline(l)}</p>`:''}).join('')+'</div>'}
const categories=[['basics','세계와 생물학',e=>e.id<=12||e.id===160],['series','시리즈와 챔피언십',e=>(e.id>=13&&e.id<=27)||[78,83].includes(e.id)],['teams','팀과 계약',e=>e.id>=28&&e.id<=35],['rules','규정과 전략',e=>(e.id>=36&&e.id<=51)||[77,80].includes(e.id)],['people','인물과 관계',e=>racers.some(r=>r.id===e.id)||[158,159,170].includes(e.id)],['culture','무대와 용어',e=>[147,161].includes(e.id)],['schedule','공식 캘린더',e=>e.id>=172],['legacy','이전 레이스 자료',e=>e.legacy]];
function heading(en,ko,desc=''){return `<section class="page-heading"><div class="en" aria-hidden="true">${en}</div><h1>${ko}</h1>${desc?`<p>${desc}</p>`:''}</section>`}
function article(e){return `<details id="entry-${e.id}"><summary>${esc(e.title)}</summary>${prose(e.body)}</details>`}
function imagePaths(r){return window.CHARACTER_IMAGES[r.id]||{}}
function initials(r){return r.english.split(' ').map(x=>x[0]).slice(0,2).join('')}
function roster(){let shown=racers.filter(r=>group==='s5'?r.series==='S5':r.series!=='S5');main.innerHTML=heading('CHARACTERS','선수 소개','저마다의 꿈을 품고, 자신만의 궤적을 그리는 레이서들.')+`<section><div class="group-tabs" role="group" aria-label="선수 명단 선택">${[['s5','S5','엔트리 시리즈','16명'],['upper','S1–S3','상위 시리즈','8명']].map(([key,s,t,n])=>`<button class="group-tab ${group===key?'active':''}" data-group="${key}" aria-pressed="${group===key}"><strong>${s}</strong><span>${t}<small>${n}</small></span></button>`).join('')}</div><div class="group-note"><h2>${group==='s5'?'S5의 16명':'더 높은 무대의 8명'}</h2><span>${group==='s5'?'엔트리 시리즈':'S1 · S2 · S3'}</span></div><div class="roster-grid">${shown.map(r=>`<a class="racer-card" href="#character/${r.id}" style="--accent:${r.color}" aria-label="${r.name} 선수 소개"><div class="portrait">${imagePaths(r).portrait?`<img src="${esc(imagePaths(r).portrait)}" alt="${r.name}" width="832" height="1216" loading="lazy">`:`<span class="initial" aria-hidden="true">${initials(r)}</span><span class="placeholder-label">프로필 이미지 준비 중</span>`}<span class="series-tag">${r.series}</span></div><div class="card-name"><h3>${r.name}</h3><p>${esc(r.english)}</p></div></a>`).join('')}</div></section>`;}
function fullbody(r){let src=imagePaths(r)[outfit];return src?`<img src="${esc(src)}" alt="${r.name} ${outfit==='casual'?'평상복':'경기복'} 전신 일러스트">`:`<div class="fullbody-placeholder"><strong aria-hidden="true">${initials(r)}</strong><span>${outfit==='casual'?'평상복':'경기복'} 전신 일러스트<br>이미지 준비 중</span></div>`}
function character(id){let r=racers.find(r=>r.id===+id);if(!r){location.hash='racers';return}group=r.series==='S5'?'s5':'upper';let list=racers.filter(p=>group==='s5'?p.series==='S5':p.series!=='S5');let n=list.indexOf(r);let blocks=r.sections||r.body.split('\n').filter(Boolean).map(t=>{let p=t.indexOf(':');return {title:p>0?t.slice(0,p):'선수 이야기',text:p>0?t.slice(p+1):t}});main.innerHTML=`<div class="character-page" style="--accent:${r.color}"><div class="character-top"><a href="#racers/${group}" class="back-link">← ${group==='s5'?'S5 선수':'상위 시리즈 선수'} 목록</a><div class="next-prev"><a href="#character/${list[(n-1+list.length)%list.length].id}" aria-label="이전 선수">←</a><a href="#character/${list[(n+1)%list.length].id}" aria-label="다음 선수">→</a></div></div><div class="character-layout"><div class="visual-column"><div class="fullbody" id="fullbody">${fullbody(r)}</div><div class="outfit-switch" role="group" aria-label="전신 의상 선택"><button data-outfit="casual" class="${outfit==='casual'?'active':''}" aria-pressed="${outfit==='casual'}">평상복</button><button data-outfit="race" class="${outfit==='race'?'active':''}" aria-pressed="${outfit==='race'}">경기복</button></div></div><div class="character-information"><div class="class-label">${r.series} · ${group==='s5'?'엔트리 시리즈':'상위 시리즈'}</div><h1>${r.name}</h1><div class="character-english">${esc(r.english)}</div>${r.lead?`<p class="character-lead">${esc(r.lead)}</p>`:''}${r.facts?`<dl class="profile-facts">${r.facts.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>`:''}<div class="profile-intro">${inline(r.intro||'')}</div><div class="outfit-description" aria-live="polite"><h2 id="outfit-heading">${outfit==='casual'?'평상복':'경기복'}</h2><p id="outfit-description">${esc(r[outfit])}</p></div></div></div><section class="profile-story"><h2 class="section-title">더 알아보기</h2><div class="story-grid">${blocks.filter(b=>!['평상복','경기복','기본 정보'].includes(b.title)).map(b=>`<article class="story-block"><h3>${esc(b.title)}</h3><p>${inline(b.text)}</p></article>`).join('')}</div></section></div>`;document.title=r.name+' · 그랑프리 스트라이더';}
function world(){main.innerHTML=heading('WORLD','그랑프리 스트라이더의 세계','달리는 몸이 가능성을 만들고, 빛나는 궤적이 이야기가 되는 세계.')+`<section class="bottom-space"><div class="world-grid"><article class="world-card"><span class="world-number">01</span><h2>스트라이더</h2><p>초고속 달리기와 신체 제어에 적합한 체질을 가진 인간. 모두가 레이서가 되는 것은 아닙니다.</p></article><article class="world-card"><span class="world-number">02</span><h2>크레스트</h2><p>신경계와 연결되어 기류와 주변 움직임을 감지하는 선천적 감각기관입니다.</p></article><article class="world-card"><span class="world-number">03</span><h2>궤적</h2><p>충분한 속도로 달릴 때 남는 고유한 빛. 선수의 움직임을 따라 자신만의 선을 그립니다.</p></article></div><h2 class="section-title">세계의 기본 설정</h2>${entries.filter(categories[0][2]).map(article).join('')}<h2 class="section-title">레이스 너머의 무대</h2>${article(entries.find(e=>e.id===161))}</section>`;}
function calendar(){let shown=events.filter(e=>series==='ALL'||e.series===series).sort((a,b)=>a.date.localeCompare(b.date));main.innerHTML=heading('RACE CALENDAR','공식 레이스 일정','S5의 첫걸음부터 S1의 마지막 그랑프리까지.')+`<section><div class="calendar-tabs" role="group" aria-label="일정 시리즈 선택">${['ALL','S1','S2','S3','S4','S5'].map(s=>`<button data-series="${s}" class="${series===s?'active':''}" aria-pressed="${series===s}">${s==='ALL'?'전체 일정':s}</button>`).join('')}</div><div class="notice">v4.4 공식 일정 · 연도는 지정되어 있지 않습니다. 크라운과 S1 퀄리피케이션은 정규 챔피언십과 별도로 열립니다.</div>${shown.map(e=>`<div class="race-row ${e.special?'special':''}"><time class="race-date">${e.date}</time><span class="race-series">${e.series}</span><div><h3>${esc(e.koName||e.name)}</h3><p>${esc(e.place)}${e.special?' · 별도 이벤트':''}</p></div></div>`).join('')}<div class="calendar-details"><h2 class="section-title">코스와 경기 세부 정보</h2>${entries.filter(e=>e.id>=173&&(series==='ALL'||e.title.includes(series))).map(article).join('')}</div></section>`;}
function archive(cat){let c=categories.find(c=>c[0]===cat)||categories[0];main.innerHTML=heading('WORLD GUIDE','월드 가이드','인물, 문화, 경기 규정과 시즌의 모든 기록.')+`<section><div class="archive-layout"><aside class="categories" aria-label="세계관 분류">${categories.map(x=>`<a href="#archive/${x[0]}" class="${x===c?'active':''}">${x[1]}<small>${entries.filter(x[2]).length}</small></a>`).join('')}</aside><div class="articles">${c[0]==='legacy'?'<div class="notice">월드인포에 함께 수록된 이전 레이스 자료입니다. 최신 공식 일정과 대회명·코스·시기가 다를 수 있습니다.</div>':''}${entries.filter(c[2]).map(article).join('')}</div></div></section>`;}
function render(){let [page,id]=(location.hash.slice(1)||'racers').split('/');if(page==='main')return;document.title='그랑프리 스트라이더 · '+({racers:'선수 소개',world:'세계관',calendar:'레이스 일정',archive:'월드 가이드',character:'선수 소개'}[page]||'선수 소개');document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+(page==='character'?'racers':page)));if(page==='character')character(id);else if(page==='world')world();else if(page==='calendar')calendar();else if(page==='archive')archive(id);else{if(['s5','upper'].includes(id))group=id;roster()}}
document.addEventListener('click',e=>{let g=e.target.closest('[data-group]');if(g){group=g.dataset.group;roster();return}let s=e.target.closest('[data-series]');if(s){series=s.dataset.series;calendar();return}let b=e.target.closest('[data-outfit]');if(b){outfit=b.dataset.outfit;let id=location.hash.split('/')[1],r=racers.find(r=>r.id===+id);document.querySelector('#fullbody').innerHTML=fullbody(r);document.querySelectorAll('[data-outfit]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});document.querySelector('#outfit-heading').textContent=outfit==='casual'?'평상복':'경기복';document.querySelector('#outfit-description').textContent=r[outfit]}});window.addEventListener('hashchange',()=>{outfit='race';render();if(location.hash!=='#main')window.scrollTo(0,0)});render();

